import "./globals.scss";
import { Inter } from "next/font/google";

import style from "./layout.module.scss";
import Logo from "@/components/svg/Logo";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className={style.logo}>
          <Logo color={"#ffffff"} />
        </header>
        {children}
      </body>
    </html>
  );
}
